# Generated by Django 4.0.3 on 2022-03-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50, verbose_name='Названия темы')),
            ],
            options={
                'verbose_name': 'Тема тестирования',
                'verbose_name_plural': 'Темы тестирования',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('test_solved', models.BooleanField(default=False, verbose_name='тест решен (для пользователя)')),
                ('question_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topictesting', verbose_name='Вопрос по теме')),
            ],
            options={
                'verbose_name': 'Вопрос темы',
                'verbose_name_plural': 'Вопросы по темам',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_choice', models.CharField(max_length=1000, verbose_name='Неверный ответ')),
                ('right_choice', models.CharField(max_length=1000, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответов',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
